---
title: "LING5503 語言的邏輯分析"
author: "謝舒凱 臺大語言學研究所"
subtitle: "LING5503 Logical Analysis of Language"
---

# 👏 歡迎


- Room: 綜 302 

- Office hours: By appointment

- Email: `shukaihsieh@ntu.edu.tw`

- Time: 09:10-12:10, Fri.

## 📜 課程網站

- [NTU COOL](https://cool.ntu.edu.tw/courses/38069)：指定教材、作業繳交

- [課程網站](lopentu.github.io/lal2024/)



## 📝 課程目的

- 瞭解語言分析的方式

- 認識世界語言的多樣性

- 學習不插電的計算語言思維


## 🏪 時程

| 時間        | 主題               | 課堂練習         |     
|:-----------:|:-----------:|:-------------:|
| W1: 02/22  | 課程介紹            |         |        
| W2: 03/01 | 語言類型與文化邏輯   |         |        
| W3: 03/08  |  語音的世界          |         |       
| W4: 03/15   | 語音的世界         |                   |
| W5: 03/22   | 構詞 |                |
| W6: 03/29   | 句法           |        | 
| W7: 04/05  |  清明節放假                |  |
| W8: 04/12   | 構詞句法       |            |                  
| W9: 04/19   | 語意、文化與詞彙                     | |            
| W10: 04/26   | 期中考**    |          |
| W11: 05/03   | 語言中的數字系統    |         | 
| W12: 05/10  | 語意與文化 ||
| W13: 05/17  |世界文字系統||
| W14: 05/24 |人造語文系統||
| W15: 05/31 |語言謎題設計||
| W16: 06/07 |期末專題報告||


::: {.callout-tip}
## APLO (https://aplo.asia/) Asia Pacific Linguistics Olympiad (APLO) 
a regional linguistics olympiad with the aim of escalating attention to language and linguistics in the Asia Pacific region. The upcoming APLO will be held on April 7th, 2024.  
:::


---

## 🐇 要求 | Requirement

- 原則上共有4份課後練習作業。截止日爲隔週四晚上 12:00，上傳至 NTU COOL。

- 期中考在 `4/26`。(從 **APLO 2024** 任挑一題做，另外一題可帶回家寫。)

- 尚須完成一個期末專案。

---

## 🏆 成績 | Grading

- 課堂參與 | Participation: 10%
- 平時作業 | Assignments: 20%
- 期中考 | Midterm: 30% 
- 期末專題與發表 | Final Project/Presentation: 40%

**遲交作業處理**

截止時間起，每天扣 5% 。有特殊事宜應該事先告知老師或助教。

## 😢 學術倫理 | Plagiarism

請大家自重自愛，不用別人要求。

## 🧠 期末報告 | Term project

- 可以個人或團體完成 (3 人以內)

    - 設計類似語奧題目，並附上清楚的語料來源與解題說明。
    
    - 設計與實作語言遊戲，不拘形式。

